version: '3.8'

services:
  nhif-app:
    build: .
    container_name: nhif-registration-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=file:/app/database/nhif_registration.db
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=https://yourdomain.com,http://localhost:3000
    volumes:
      - ./database:/app/database
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nhif-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - nhif-app
    restart: unless-stopped
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nhif-frontend
    ports:
      - "3000:3000"
    depends_on:
      - nhif-app
    restart: unless-stopped
